apiVersion: v1
kind: Template
labels:
  template: mongodb-persistent-template
metadata:
  annotations:
    openshift.io/display-name: MongoDB
    tags: database,mongodb
  name: mongodb-persistent
objects:
- apiVersion: v1
  kind: Secret
  metadata:
    annotations:
      template.openshift.io/expose-admin_password: "{.data['database-admin-password']}"
      template.openshift.io/expose-database_name: "{.data['database-name']}"
      template.openshift.io/expose-password: "{.data['database-password']}"
      template.openshift.io/expose-username: "{.data['database-user']}"
    name: "mongodb"
    labels:
      app: mongodb
  stringData:
    database-admin-password: "${MONGODB_ADMIN_PASSWORD}"
    database-name: "${MONGODB_DATABASE}"
    database-password: "${MONGODB_PASSWORD}"
    database-user: "${MONGODB_USER}"
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      template.openshift.io/expose-uri: mongodb://{.spec.clusterIP}:{.spec.ports[?(.name=="mongo")].port}
    name: "mongodb"
    labels:
      app: mongodb
  spec:
    ports:
    - name: mongo
      nodePort: 0
      port: 27017
      protocol: TCP
      targetPort: 27017
    selector:
      name: "mongodb"
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: "mongodb"
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    annotations:
      template.alpha.openshift.io/wait-for-ready: 'true'
    name: "mongodb"
    createionTimestamp: null
    labels:
      template: mongodb-persistent-template
  spec:
    replicas: 1
    selector:
      name: "mongodb"
    strategy:
      type: Recreate
    template:
      metadata:
        labels:
          name: "mongodb"
      spec:
        containers:
        - capabilities: {}
          env:
          - name: MONGODB_USER
            valueFrom:
              secretKeyRef:
                key: database-user
                name: "mongodb"
          - name: MONGODB_PASSWORD
            valueFrom:
              secretKeyRef:
                key: database-password
                name: "mongodb"
          - name: MONGODB_ADMIN_PASSWORD
            valueFrom:
              secretKeyRef:
                key: database-admin-password
                name: "mongodb"
          - name: MONGODB_DATABASE
            valueFrom:
              secretKeyRef:
                key: database-name
                name: "mongodb"
          image: "centos/mongodb-32-centos7"
          imagePullPolicy: IfNotPresent
          livenessProbe:
            initialDelaySeconds: 30
            tcpSocket:
              port: 27017
            timeoutSeconds: 1
          name: mongodb
          ports:
          - containerPort: 27017
            protocol: TCP
          readinessProbe:
            exec:
              command:
              - "/bin/sh"
              - "-i"
              - "-c"
              - mongo 127.0.0.1:27017/$MONGODB_DATABASE -u $MONGODB_USER -p $MONGODB_PASSWORD
                --eval="quit()"
            initialDelaySeconds: 3
            timeoutSeconds: 1
          resources:
            limits:
              memory: 512Mi
          securityContext:
            capabilities: {}
            privileged: false
          terminationMessagePath: "/dev/termination-log"
          volumeMounts:
          - mountPath: "/var/lib/mongodb/data"
            name: "mongodb-data"
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        volumes:
        - name: "mongodb-data"
          persistentVolumeClaim:
            claimName: "mongodb"
    triggers:
    - type: ConfigChange
    status: {}
parameters:
- description: Username for MongoDB user that will be used for accessing the database.
  displayName: MongoDB Connection Username
  name: MONGODB_USER
  value: mongodb
  required: true
- description: Password for the MongoDB connection user.
  displayName: MongoDB Connection Password
  name: MONGODB_PASSWORD
  value: mongodb
  required: true
- description: Name of the MongoDB database accessed.
  displayName: MongoDB Database Name
  name: MONGODB_DATABASE
  required: true
  value: parks
- description: Password for the database admin user.
  displayName: MongoDB Admin Password
  from: "[a-zA-Z0-9]{16}"
  generate: expression
  name: MONGODB_ADMIN_PASSWORD
  required: true
- description: Volume space available for data, e.g. 512Mi, 2Gi.
  displayName: Volume Capacity
  name: VOLUME_CAPACITY
  required: true
  value: 1Gi
- description: Version of MongoDB image to be used (3.6 or latest).
  displayName: Version of MongoDB Image
  name: MONGODB_VERSION
  required: true
  value: 'latest'
